#!/usr/bin/env python3
import pathlib,json,html,shutil
r=pathlib.Path(__file__).resolve().parents[1];w=r/'web'
nav=[('index','Home'),('features','Features'),('how-it-works','How it works'),('ecosystem','Ecosystem'),('project','Project'),('documentation','Docs'),('privacy','Privacy')]
def page(slug,title,content):
 content=content.replace('<pre>','<pre tabindex="0" role="region" aria-label="Local command block">')
 links=''.join(f'<a href="{s}.html"'+(' aria-current="page"' if s==slug else '')+f'>{t}</a>' for s,t in nav)
 (w/(slug+'.html')).write_text(f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} · Deproof</title><meta name="description" content="Local-first noncustodial review and portable evidence. Actual qualification status, Built by CodesbyFebin."><link rel="stylesheet" href="style.css"><script src="inspect.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header><a class="brand" href="index.html"><img src="assets/depr.svg" alt="DEPR">DEPROOF</a><nav aria-label="Main">{links}</nav></header><main id="main" tabindex="-1">{content}</main><footer><span>Built by CodesbyFebin</span><span>$DEPR — Brand concept · No token issuance</span><a href="project.html">Qualification &amp; source</a></footer></body></html>')
(w/'assets').mkdir(exist_ok=True);shutil.copyfile(r/'assets/depr.svg',w/'assets/depr.svg')
shutil.copyfile(r/'docs/blueprint/DEPROOF_MASTER_BLUEPRINT_AND_DESIGN/assets/reference/deproof-30-solutions-showcase.png',w/'assets/concept.png')
page('index','Review. Sign. Verify.', '''<section class="hero"><p class="eyebrow">Local control / clear provenance</p><h1>See the action.<br><span class="accent">Keep the record.</span></h1><p class="lead">One workspace. Clearer records. Connected ecosystems as they qualify.</p><p>Deproof brings transaction review, private evidence and user-owned node control into a portable project. Qualification is recorded per component. Device, hosting and external network gates remain incomplete.</p><div class="actions"><a class="button" href="documentation.html">Build &amp; verify locally ↗</a><a class="button secondary" href="project.html">Inspect implementation status</a></div><span class="tag">Development build • Debug APK produced; device qualification pending</span></section><div class="grid"><article class="panel"><span class="index">01 / REVIEW</span><h2>Every byte matters.</h2><p>Exact message binding and strict instruction refusal. Wallet keys stay in the wallet.</p></article><article class="panel"><span class="index">02 / EVIDENCE</span><h2>Integrity, precisely.</h2><p>Raw-file hashes and portable manifests. A signature supports integrity; it does not establish physical truth.</p></article><article class="panel"><span class="index">03 / CONTROL</span><h2>Your node. Your scope.</h2><p>Scoped pairing, authenticated commands and consent defaults. External network rewards remain unconfigured.</p></article></div><figure><img src="assets/concept.png" alt="Concept artwork showing the thirty ecosystem requirements" loading="lazy"><figcaption>Concept reference only. Four-tab preview and promotional measurements do not describe runtime state. Native navigation remains Now / Review / Receipts.</figcaption></figure>''')
features=json.loads((r/'features.json').read_text())['features']
rows=''.join(f'<tr data-search="{html.escape((f["id"]+" "+f["definition"]+" "+f["status"]).lower())}"><td>{f["id"]}</td><td>{html.escape(f["definition"])}</td><td>{f.get("phase","P1")}</td><td>{f["status"]}</td></tr>' for f in features)
page('features','Feature registry',f'<p class="eyebrow">Authoritative registry</p><h1>120 base features.</h1><p>100 overlapping core checks, 30 ecosystem requirements and 86 function contracts are tracked separately. Counts do not imply completion.</p><label for="filter">Search ID, behavior or status</label><input id="filter" type="search" placeholder="For example, F045 or BLOCKED"><p id="filter-count" aria-live="polite"></p><div class="table-scroll" tabindex="0" role="region" aria-label="Feature registry table"><table><thead><tr><th>ID</th><th>Behavior</th><th>Phase</th><th>Status</th></tr></thead><tbody>{rows}</tbody></table></div>')
page('how-it-works','How it works','''<p class="eyebrow">Three destinations / distinct assurance</p><h1>Review. Sign. Verify.</h1><div class="flow"><article><h2>Observe</h2><p>Query an address. Display attributable slot/time and independent errors. Observation does not connect a wallet.</p></article><article><h2>Review</h2><p>Inspect every instruction, complete message and review context. Unsupported siblings refuse the whole action.</p></article><article><h2>Authorize</h2><p>On a qualified device, the wallet returns signed bytes. Compare message and verify signatures before RPC submission.</p></article><article><h2>Retain</h2><p>Keep a persistent event and separate observations. Submission, confirmation and local evidence are different claims.</p></article></div><h2>Tasks and evidence</h2><p>Create local tasks, track checklists, import files and preserve exact notes. Export manifests and receipts for independent inspection. Device capture and process recovery still need qualification.</p><h2>Inspect a receipt locally</h2><p>The inspector reads JSON in your browser and makes no network call. It displays recorded provenance; it does not cryptographically verify it. Run the independent offline CLI for signature and file integrity.</p><label for="receipt-file">Choose a receipt JSON file</label><input id="receipt-file" type="file" accept="application/json,.json"><label for="receipt-text">Or paste receipt JSON</label><textarea id="receipt-text" spellcheck="false"></textarea><button id="inspect" type="button">Inspect recorded provenance</button><output id="inspection" aria-live="polite">No record selected.</output>''')
ecos=json.loads((r/'ecosystem-requirements.json').read_text())['requirements'];groups=['Solana Mobile','SKR workspace','Edge & local hosting','Bandwidth sharing','Prover network','Evidence & control'];cards=''
for i,group in enumerate(groups):
 items=''.join(f'<details><summary>{e["id"]} · {html.escape(e["name"])}</summary><p><span class="tag">{e["status"]}</span></p><p>{html.escape(e["acceptance"])}</p><p>{html.escape("; ".join(e["limitations"]))}</p></details>' for e in ecos[i*5:i*5+5]);cards+=f'<article class="panel"><span class="index">{i+1:02d} / ECOSYSTEM</span><h2>{group}</h2>{items}</article>'
page('ecosystem','Ecosystem',f'<p class="eyebrow">Own your node / prove your contribution</p><h1>One workspace.<br>Thirty requirements.</h1><p>Local measurements, signatures, verified cryptographic statements and external settlement remain distinct. No partnership or reward entitlement is implied.</p><div class="grid">{cards}</div><h2>Provider catalogue</h2><p>Wallets, DeFi, liquid staking, DePIN, storage and explorers remain an external provider layer. Only the implemented MWA adapter and Solana RPC client have source here; device/protocol qualification is incomplete. Additional adapters are blocked pending current scoped interfaces and credentials where required.</p>')
page('project','Explore project','''<p class="eyebrow">Open source / local delivery</p><h1>Inspect the work.</h1><p>Source, schemas, tests and qualification logs are delivered in this repository. Nothing has been deployed or published from this implementation run.</p><div class="grid"><article class="panel"><h2>Android</h2><p>Kotlin / Compose, Room, DataStore and MWA source. Host debug build qualification is recorded in the current report. Physical-device qualification remains NOT_RUN. Container builds have separate scoped evidence.</p></article><article class="panel"><h2>Node agent</h2><p>Real authenticated local TLS API, consent/quota and metering checks have recorded scope-specific evidence. Hosting qualification is limited to the tested fixed Docker profile; external providers remain unqualified.</p></article><article class="panel"><h2>Portable tools</h2><p>Independent Python verifier and cross-language vectors; actual local educational proof generation and separate verification. Production proof-system and external-provider qualification remain incomplete.</p></article></div><h2>Local delivery files</h2><ul><li><a href="../evidence/qualification/qualification-report.md">Qualification report</a></li><li><a href="../evidence/qualification/implementation-status.json">Machine-readable status</a></li><li><a href="../evidence/qualification/artifact-checksums.txt">Artifact checksums</a></li><li><a href="../docs/threat-model.md">Threat model</a></li><li><a href="../docs/dependency-decisions.md">Dependency decisions</a></li><li><a href="../LICENSE">Proposed source license</a></li></ul><p>Serve from the repository root to follow repository-relative document links. Imported reference asset rights remain unresolved. No release signing credentials or public repository URL have been invented.</p>''')
page('documentation','Documentation','''<p class="eyebrow">Reproducible setup</p><h1>Build your own.</h1><h2>Android</h2><pre>./scripts/setup-android.sh\n./gradlew assembleDebug testDebugUnitTest lintDebug</pre><p>Requires JDK 17, Android SDK 37.0, build tools 36.0.0, dependency access and normal local socket permissions. The configured identity http://localhost is a local development identity; configure a developer-controlled HTTPS URL before release.</p><h2>Local qualification</h2><pre>./scripts/qualify.sh\npython3 scripts/qualify-core.py\n./scripts/qualify-node.sh\npython3 -m unittest discover -s tools</pre><h2>Offline integrity</h2><pre>python3 -m pip install -r tools/requirements.txt\npython3 tools/verify.py receipt.json --files /path/to/private-files</pre><p>Private files use stable manifest IDs as filenames. Missing files are NOT_RUN. The verifier does not query chain settlement or establish physical truth.</p><h2>Owner-controlled node</h2><pre>node-agent/build/deproof-node --state /private/owner/node</pre><p>Loopback TLS only. Copy the generated certificate through an owner-approved local channel and approve the node fingerprint. Pairing code expires after two minutes. Hosting/prover operations fail with named blockers until their runtimes qualify.</p><p><a href="../docs/setup.md">Detailed setup and manual device gates</a> · <a href="../docs/ecosystem/node.md">Node operation and consent</a></p>''')
page('privacy','Privacy','''<p class="eyebrow">Private by default</p><h1>Keep control<br>of your records.</h1><h2>Local evidence</h2><p>Imported files and task records stay in app-private storage. No evidence upload, location collection or AI transmission is enabled. System camera capture happens only when explicitly launched. Deleting a local record cannot retract an export already shared.</p><h2>Network observations</h2><p>RPC providers receive queried addresses, transaction signatures and explicitly approved devnet transaction bytes. Their response is an observation with source/freshness limits. Wallet authorization stays between the app and the installed wallet. Tokens are kept only in memory and excluded from exports.</p><h2>Node control</h2><p>Node keys use permission-restricted files, disclosed as software storage. Pairing authorizes selected scopes. Bandwidth is disabled by default and after restart. An owner-allowlisted receiver and explicit caps are required; local counters do not imply reward acceptance.</p><h2>Retention and recovery</h2><p>Android backup is disabled. Export public verification material and receipts intentionally. Evidence private keys are not portable and are never exported. Lost-device recovery does not recover wallet secrets or reverse transactions.</p><p><a href="../docs/privacy.md">Full implementation privacy record</a> · <a href="../SECURITY.md">Security reporting</a></p>''')
print('Built 7 local pages; no deployment performed.')
