#!/usr/bin/env python3
import json,pathlib,hashlib
root=pathlib.Path(__file__).resolve().parents[1]
def write(name,obj):
 p=root/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
def obj(props,required=None):return {'type':'object','additionalProperties':False,'properties':props,'required':list(props) if required is None else required}
def text(pattern=None):return {'type':'string',**({'pattern':pattern} if pattern else {})}
def nullable(schema):return {'anyOf':[schema,{'type':'null'}]}
def enum(*vals):return {'enum':list(vals)}
digest=text('^[0-9a-f]{64}$');counter=text('^(0|[1-9][0-9]*)$');stamp=text(r'^\d{4}-\d{2}-\d{2}T.*Z$');uuid={'type':'string','format':'uuid'}
file=obj({'id':text('^[A-Za-z0-9_-]{1,80}$'),'sha256':digest,'mime':text(),'byteLength':counter,'provenance':enum('import','capture')})
manifest=obj({'schema':{'const':'deproof-evidence-v2'},'taskId':nullable(uuid),'messageSha256':nullable(digest),'files':{'type':'array','maxItems':100,'items':file},'note':text(),'createdAt':stamp})
local=obj({'domain':{'const':'deproof-evidence-sig-v2'},'algorithm':{'const':'SHA256withECDSA'},'envelopeBase64':text(),'signatureDerBase64':text(),'spkiBase64':text(),'aliasVersion':text(),'securityLevel':enum('STRONGBOX','TRUSTED_ENVIRONMENT','HARDWARE_UNSPECIFIED','SOFTWARE','UNAVAILABLE'),'qualification':text()})
receipt=obj({'schema':{'const':'deproof-receipt-v2'},'id':uuid,'taskId':nullable(uuid),'outcome':enum('REJECTED','OBSERVED','LOCAL_EVIDENCE_SIGNED','WALLET_SIGNED','SUBMITTED'),'account':nullable(text()),'network':nullable(enum('devnet','mainnet-beta')),'summary':text(),'cardHash':nullable(digest),'messageSha256':nullable(digest),'currentMessageSha256':nullable(digest),'reviewContextHash':nullable(digest),'evidenceDigest':nullable(digest),'manifest':nullable(manifest),'signature':nullable(text()),'localSignature':nullable(local),'submission':obj({'state':enum('NOT_SUBMITTED','SUBMITTING','SUBMITTED','SUBMISSION_UNKNOWN'),'submittedByDeproof':nullable({'type':'boolean'}),'broadcast':nullable({'type':'boolean'}),'attemptedAt':nullable(stamp),'rpcAcceptedAt':nullable(stamp)}),'chainObservation':obj({'availability':enum('AVAILABLE','UNAVAILABLE','NOT_QUERIED'),'lastKnownStatus':enum('UNKNOWN','PROCESSED','CONFIRMED','FINALIZED','FAILED'),'slot':nullable(counter),'blockTime':nullable(counter),'observedAt':nullable(stamp),'error':{}}),'policyVersion':nullable(text()),'decoderVersion':text(),'createdAt':stamp,'limitations':{'type':'array','items':text()}})
receipt['allOf']=[{'if':{'properties':{'outcome':{'const':'REJECTED'}}},'then':{'properties':{'signature':{'type':'null'},'submission':{'properties':{'state':{'const':'NOT_SUBMITTED'},'broadcast':{'const':False},'submittedByDeproof':{'const':False}}}}}},{'if':{'properties':{'outcome':{'const':'OBSERVED'}}},'then':{'properties':{'submission':{'properties':{'state':{'const':'NOT_SUBMITTED'},'broadcast':{'const':False},'submittedByDeproof':{'const':False}}}}}}]
for name,s in [('evidence-v2',manifest),('receipt-v2',receipt),('evidence-envelope-v2',obj({'domain':{'const':'deproof-evidence-sig-v2'},'manifestDigest':digest,'manifestSchema':{'const':'deproof-evidence-v2'},'algorithm':{'const':'SHA256withECDSA'}}))]:write('contracts/'+name+'.schema.json',{'$schema':'https://json-schema.org/draft/2020-12/schema',**s})
ecosystem={
'NodeIdentity':{'schema':{'const':'deproof-node-identity-v1'},'publicKeyBase64':text(),'fingerprint':digest,'keyProtection':text(),'createdAt':stamp},
'PairingChallenge':{'id':text(),'nonce':text(),'fingerprint':digest,'expiresAt':stamp},
'ServiceProfile':{'schema':{'const':'deproof-service-profile-v1'},'id':text(),'artifactDigest':digest,'runtime':text(),'cpuMilli':counter,'memoryBytes':counter,'pids':counter,'diskBytes':counter,'network':{'const':'none'},'readOnly':{'const':True},'nonRootUid':counter,'hostPorts':{'type':'array','maxItems':0},'mounts':{'type':'array','maxItems':0},'healthCommand':{'type':'array','items':text()}},
'NodeObservation':{'schema':{'const':'deproof-node-observation-v1'},'nodeFingerprint':digest,'observedAt':stamp,'hostOS':text(),'architecture':text(),'logicalCPUs':counter,'desiredState':text(),'observedState':text(),'runtimeIdentity':nullable(text()),'limitations':{'type':'array','items':text()}},
'SharingConsent':{'enabled':{'type':'boolean'},'endpoint':text(),'capBytes':counter,'reservedBytes':counter,'measuredBytes':counter,'bytesPerSecond':counter,'deadline':stamp},
'MeteringEnvelope':{'domain':{'const':'deproof-metering-v1'},'nodeFingerprint':digest,'operationId':text(),'sequence':counter,'endpoint':text(),'reservedBytes':counter,'measuredBytes':counter,'unit':text(),'durationNs':counter,'startedAt':stamp,'endedAt':stamp,'outcome':text(),'peerAcknowledgment':nullable({'type':'object'}),'reward':nullable({'type':'object'}),'assurance':text()},
'PeerAcknowledgment':{'domain':{'const':'deproof-peer-ack-v1'},'producerFingerprint':digest,'peerFingerprint':digest,'operationId':text(),'acceptedBytes':counter,'observedAt':stamp,'meteringDigest':digest},
'ProofJob':{'schema':{'const':'deproof-proof-job-v1'},'id':text(),'backend':text(),'scheme':text(),'circuitDigest':digest,'verificationKeyDigest':digest,'inputCommitment':digest,'publicInputs':{'type':'object'},'maxWitnessBytes':counter,'deadline':stamp,'source':text(),'compensation':nullable({'type':'object'})},
'ProofResult':{'schema':{'const':'deproof-proof-result-v1'},'jobId':text(),'backend':text(),'circuitDigest':digest,'verificationKeyDigest':digest,'proofDigest':digest,'publicInputsDigest':digest,'producerFingerprint':digest,'completedAt':stamp},
'VerificationObservation':{'schema':{'const':'deproof-proof-verification-v1'},'proofDigest':digest,'verificationKeyDigest':digest,'publicInputsDigest':digest,'verifier':text(),'trustDomain':text(),'status':enum('PASS','FAIL','BLOCKED','NOT_RUN'),'observedAt':stamp,'limitations':{'type':'array','items':text()}},
'ContributionReceipt':{'schema':{'const':'deproof-contribution-v1'},'id':uuid,'producerFingerprint':digest,'jobId':nullable(text()),'inputCommitment':nullable(digest),'resultDigest':nullable(digest),'meteringDigest':nullable(digest),'verificationObservation':nullable({'type':'object'}),'chainObservation':nullable({'type':'object'}),'assurance':text(),'createdAt':stamp},
'PayoutObservation':{'schema':{'const':'deproof-payout-observation-v1'},'provider':text(),'asset':text(),'mint':nullable(text()),'cluster':text(),'accrued':nullable(counter),'claimable':nullable(counter),'paid':nullable(counter),'signature':nullable(text()),'observedAt':stamp,'source':text()}}
for name,s in ecosystem.items():write('contracts/ecosystem/'+name+'.schema.json',{'$schema':'https://json-schema.org/draft/2020-12/schema',**obj(s)})
# Synthetic canonicalization vectors; signatures and chain data are deliberately absent.
inputs=[{'z':'é\n','a':None},{'😀':'astral','\ue000':'bmp','note':'नमस्ते\nline 2'},{'schema':'deproof-evidence-v2','taskId':None,'messageSha256':None,'files':[],'note':' exact\n note 😀 ','createdAt':'2026-10-06T00:00:00Z'}]
import sys
sys.path.insert(0,str(root/'tools'))
from verify import canonical
write('fixtures/jcs-vectors.json',[{'label':'SYNTHETIC_CANONICALIZATION_VECTOR','input':v,'canonical':canonical(v).decode(),'sha256':hashlib.sha256(canonical(v)).hexdigest()} for v in inputs])
write('fixtures/transfer-checked-vectors.json',[{'label':'SYNTHETIC_SPL_LAYOUT_VECTOR','amountRaw':str(n),'decimals':'6','hex':(bytes([12])+n.to_bytes(8,'little')+bytes([6])).hex()} for n in [0,1,1000000000,2**63,2**64-1]])
