#!/usr/bin/env python3
"""Evidence-backed local qualification. Build, device and external assurance stay separate."""
import collections,datetime,hashlib,json,pathlib,zipfile
r=pathlib.Path(__file__).resolve().parents[1];out=r/'evidence/qualification';out.mkdir(parents=True,exist_ok=True)
def hashfile(p):return hashlib.sha256(p.read_bytes()).hexdigest()
commands=[json.loads(x) for x in (out/'command-results.jsonl').read_text().splitlines()]
latest={x['gate']:x for x in commands};passed={n for n,x in latest.items() if x['exitCode']==0}
coverage={}
for name,key in [('features','features'),('core-checks','checks'),('functions','functions'),('ecosystem-requirements','requirements')]:
 d=json.loads((r/(name+'.json')).read_text());coverage[name]=d['base']+d['ecosystem'] if name=='functions' else d[key]
counts={n:dict(collections.Counter(x['status'] for x in entries)) for n,entries in coverage.items()}
blockers=[
 {'id':'DEVICE_WALLET_HARDWARE','qualification':'NOT_RUN','reason':'ADB lists no connected physical device. MWA signing, Keystore protection/security level, Room-on-device migration and process-death/camera tests remain unrun.','recovery':'Connect a supported device; run python3 scripts/qualify-device.py and follow docs/device-qualification.md. No automated mainnet transaction.'},
 {'id':'HOST_SUPPORT_MATRIX','qualification':'BLOCKED','reason':'Only the documented constrained HTTP profile on this local Linux Docker VM is qualified. The owner-trusted Docker engine is rootful; rootless engines, native Linux/ARM64 targets and arbitrary services are unqualified.'},
 {'id':'EXTERNAL_PEER_PROVIDER','qualification':'NOT_RUN','reason':'Real loopback TLS pairing and controlled known-byte receiver passed locally; remote peer tunnels, NAT/mobile network transitions, provider corroboration and payouts remain untested.'},
 {'id':'PROOF_PRODUCTION_SETUP','qualification':'NOT_RUN','reason':'Owner-signed local cubic jobs and separate gnark verifier pass. Educational trusted setup and same-owner verifier domain; isolated production proof execution, external jobs/provider membership/rewards remain unqualified.'},
 {'id':'P5_EXTERNAL_ADAPTERS','qualification':'BLOCKED','reason':'Verified SKR staking layouts and additional provider authorization/protocol interfaces unavailable. No mainnet spending.'},
 {'id':'SOURCE_COMPLETENESS','qualification':'NOT_RUN','reason':'Full lookup resolution, legacy receipt import, unsupported media previews/capture lifecycle, device validation of newly implemented consented location/offline mapping/reminders, complete dynamic translations, background network policy and physical document-provider/crash acceptance for bounded Android backups remain incomplete. Bounded text/image previews are implemented but not device-qualified. Each unresolved registry entry is listed in uncovered-requirements.json.'},
 {'id':'RELEASE_AND_RIGHTS','qualification':'BLOCKED','reason':'No release signing or physical-device release checks; comprehensive SBOM/advisory and imported-asset rights review incomplete.'}]
for gate,id in [('android-build','ANDROID_BUILD'),('node-integration','NODE_INTEGRATION'),('hosting-isolation','HOST_ISOLATION'),('prover-tests','PROOF_BACKEND'),('browser-checks','BROWSER_AUTOMATION'),('rpc-read-only','LIVE_RPC')]:
 if gate not in passed:blockers.append({'id':id,'qualification':'BLOCKED' if gate not in latest else 'FAIL','reason':'Named gate has no passing result. Inspect '+str(latest.get(gate,{}).get('log','missing command evidence'))+'. No successful behavior inferred.'})
blockers.append({'id':'EXPLANATION_PROVIDER','qualification':'BLOCKED','reason':'Typed consent/configuration/error guard exists; no qualified external explanation adapter or outbound request is registered. Guard tests do not establish provider integration.'})
blockers.append({'id':'MANUAL_ACCESSIBILITY','qualification':'NOT_RUN','reason':'Automated Chromium/axe/keyboard/200% text checks do not establish full manual screen-reader, cross-browser or Android accessibility qualification.'})
container_report=r/'evidence/docker/qualification-summary.json'
container=json.loads(container_report.read_text()) if container_report.is_file() else None
if container and container['status']!='PASS':
 blockers.append({'id':'CONTAINER_QUALIFICATION','qualification':container['status'],'reason':'See evidence/docker/qualification-summary.json. Service images and portable checks passed; Docker storage is exhausted, Android cache ownership correction is untested, container APK absent and final owner-control revisions remain unqualified. Host Android build passes do not establish container build success.'})
artifacts=[]
def artifact(p,kind):
 if p.is_file():artifacts.append({'path':str(p.relative_to(r)),'kind':kind,'sha256':hashfile(p),'bytes':str(p.stat().st_size)})
for path,kind in [('app/build/outputs/apk/debug/app-debug.apk','debug-apk'),('node-agent/build/deproof-node','darwin-amd64-node-binary'),('prover-worker/build/prove','local-proof-producer'),('prover-worker/build/verify','independent-proof-verifier'),('gradle/wrapper/gradle-wrapper.jar','gradle-wrapper'),('tools/verify.py','independent-receipt-verifier')]:artifact(r/path,kind)
for p in (r/'prover-worker/build').glob('qualified-result-*/*'):artifact(p,'local-proof-artifact')
for p in (out/'browser').glob('*.png'):artifact(p,'browser-evidence-screenshot')
levels={'BUILD_QUALIFIED':'android-build' in passed and (r/'app/build/outputs/apk/debug/app-debug.apk').is_file(),'CORE_DEVICE_QUALIFIED':False,'FULL_SCOPE_QUALIFIED':False}
status={'sourceManifest':'evidence/qualification/source-before.json','schema':'deproof-implementation-status-v1','generatedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'product':'Deproof','mark':'DEPR','credit':'Built by CodesbyFebin','brandConcept':'$DEPR; no token issuance','qualificationLevels':levels,'authoritativeCounts':{'baseFeatures':120,'coreChecks':100,'baseContracts':62,'ecosystemRequirements':30,'ecosystemContracts':24,'totalFunctionContracts':86},'overlapPolicy':'F/E/C overlap; not additional unique features.','countsByRegistry':counts,'commands':commands,'blockers':blockers,'artifacts':artifacts,'coverage':coverage,'performedMainnetSpending':False,'publishedOrDeployed':False,'prioritizedBacklog':'evidence/qualification/prioritized-backlog.json','deviceQualification':'evidence/qualification/device-qualification.json','containerQualification':'evidence/docker/qualification-summary.json'}
lines=['# Local qualification report','','Deproof / DEPR — Built by CodesbyFebin. $DEPR remains a brand concept only.','',f'BUILD_QUALIFIED: **{levels["BUILD_QUALIFIED"]}**. CORE_DEVICE_QUALIFIED: **False**. FULL_SCOPE_QUALIFIED: **False**. Automated passes do not establish production readiness.','','## Implemented components','','- Kotlin/Compose Now, Review and Receipts with nested Nodes, Bandwidth and Proof jobs. Real pinned-TLS node client, exact-byte Ed25519 pairing/commands, independently pinned node identity, encrypted node-control seed and durable command records; no wallet secrets.','- Room v1→v2 additive migration; existing event/task/evidence bytes preserved. Submission/command recovery never automatically replays uncertain effects. File-ready import journal verifies bytes before recovery. Device lifecycle remains unrun.','- Go agent with scoped pairing, self/owner revocation, observed host state, fixed-endpoint consent, persistent reservations, actual transfers, stop/cancellation and signed metering.','- Qualified cached BusyBox isolated HTTP service profile on the local Linux VM: real start/health/stop and restart reconciliation; no public ports/mounts/network, nonroot, read-only root, dropped capabilities, CPU/memory/PID/tmpfs limits. Rootful owner-trusted engine disclosed.','- Owner-signed bounded local proof discovery, pinned circuit/key, actual producer and separate verifier; tampered proof/key/input/job/receipt rejection; signed contribution receipts with explicit same-owner/educational assurance.','- Read-only live app RPC observations for both public clusters. Full genesis constants corrected; failures remain unavailable rather than zero. Public System program account only; no user wallet or spending.','- Seven website routes, registry filter and local receipt inspector. Browser screenshots and automated accessibility results recorded separately from manual/device qualification.','','## Exact executed commands','','| Gate | Command | Exit | Result | Log |','|---|---|---:|---|---|']
for c in commands:lines.append(f'| {c["gate"]} | `{" ".join(c["command"])}` | {c["exitCode"]} | {"PASS" if c["exitCode"]==0 else "FAIL"} | [{c["log"]}](../../{c["log"]}) |')
lines+=['','Android script executes `bash ./gradlew testDebugUnitTest --stacktrace`, `bash ./gradlew assembleDebug --stacktrace`, and `bash ./gradlew lintDebug --stacktrace`. It hashes the APK only after these tasks succeed.','', 'Historical failures: sandbox cache/native-library/socket and DNS restrictions were cleared through approved execution. Source failures were the MWA shared namespace and unguarded StrongBox exception. The live RPC probe additionally exposed shortened genesis constants; full-hash checks now have regression tests. Historical failures are preserved in prior run logs.','','## Registry coverage','']
for n,v in counts.items():lines.append(f'- {n}: {json.dumps(v,sort_keys=True)}')
lines+=['','Exact counts remain 120 F, 100 C, 62 FN + 24 EF = 86 contracts and 30 E. `uncovered-requirements.json` enumerates each unresolved acceptance with paths/tests/evidence; local-profile verification never implies external/device qualification.','','## Unresolved qualification gates','']
for b in blockers:lines.append(f'- **{b["id"]}: {b["qualification"]}** — {b["reason"]}')
lines+=['','## Current continuation','','Authenticated bounded Room backup/export/additive restore UI, raw-file metadata association and fresh observed local proof-profile matching are wired; supporting domain/Room tests are recorded, physical document-provider/crash and Android-to-Linux dispatch remain NOT_RUN. Backup excludes private signing keys, credentials and active permissions; see docs/backup-and-proof-wiring.md. Consented foreground location with optional hash-bound metadata, private offline mapping plans and opt-in inexact task reminders are implemented. English/Spanish resource catalogs and persisted UI language selection are implemented, but full dynamic explanation localization and independent/device review remain incomplete. See docs/local-workflows.md and evidence/qualification/localization-report.json. Bounded private text/image previews, persisted first-seen program indicators, the legacy raw digest signing contract and bounded read-only account/rent explanations are implemented; supporting local tests pass, Android hardware/lifecycle acceptance remains NOT_RUN. Optional explanation consent/configuration/error guards are tested, but the external provider adapter remains BLOCKED. F097 now correctly links existing one-rebuild memo logic and fresh-review enforcement. No device pass is inferred.','','Dependency/security/environment priorities: `evidence/qualification/prioritized-backlog.json`; code/evidence gaps and next steps: `docs/remaining-work.md`. Physical preflight: `python3 scripts/qualify-device.py`; install only with `--install` and follow `docs/device-qualification.md`.','','## Produced artifacts','']
for a in artifacts:lines.append(f'- `{a["path"]}` — {a["kind"]}; SHA-256 `{a["sha256"]}`')
lines+=['','Source snapshot: `evidence/qualification/deproof-source-snapshot.zip`. Local artifact only; imported asset rights remain unresolved. No publishing, deployment, token issuance or mainnet spending occurred.']
if container:
 lines+=['','## Container development qualification','',f'Container scope: **{container["status"]}**. Detailed commands, pinned images, actual builds and blockers: `evidence/docker/qualification-summary.json` and `evidence/docker/qualification-report.md`. No container APK is claimed; existing host APK qualification remains separate. All 336 registry IDs and unavailable device/external gates are preserved.']
report='\n'.join(lines)+'\n';(out/'qualification-report.md').write_text(report);(r/'docs/status.md').write_text(report.replace('(../../evidence/','(../evidence/'))
(out/'implementation-status.json').write_text(json.dumps(status,ensure_ascii=False,indent=2)+'\n')
(out/'dependency-inventory.json').write_text(json.dumps({'schema':'deproof-dependency-inventory-v1','resolvedTransitiveSBOM':False,'android':'app/build.gradle.kts','prover':['prover-worker/go.mod','prover-worker/go.sum'],'browser':['scripts/browser/package.json','scripts/browser/package-lock.json'],'limits':['Full license/advisory/SBOM review incomplete.']},indent=2)+'\n')
source=[]
for base in ['docker','app/src','app/schemas','contracts','fixtures','tools','scripts','web','.github','docs','assets','node-agent/cmd','node-agent/internal','prover-worker/cmd','prover-worker/internal']:
 for p in (r/base).rglob('*'):
  if p.is_file() and '__pycache__' not in p.parts and 'node_modules' not in p.parts:source.append(p)
source+=list(r.glob('*.md'))
for name in ['app/build.gradle.kts','LICENSE','.gitignore','.dockerignore','compose.yaml','settings.gradle.kts','build.gradle.kts','gradle.properties','gradlew','gradlew.bat','gradle/wrapper/gradle-wrapper.jar','gradle/wrapper/gradle-wrapper.properties','node-agent/go.mod','prover-worker/go.mod','prover-worker/go.sum','features.json','core-checks.json','functions.json','ecosystem-requirements.json']:source.append(r/name)
archive=out/'deproof-source-snapshot.zip'
with zipfile.ZipFile(archive,'w',zipfile.ZIP_DEFLATED) as z:
 for p in sorted(set(source)):
  info=zipfile.ZipInfo(str(p.relative_to(r)),date_time=(2026,10,6,0,0,0));info.external_attr=(p.stat().st_mode&0xffff)<<16;info.compress_type=zipfile.ZIP_DEFLATED;z.writestr(info,p.read_bytes())
artifact(archive,'local-source-snapshot');status['artifacts']=artifacts;(out/'implementation-status.json').write_text(json.dumps(status,ensure_ascii=False,indent=2)+'\n')
files=set(source)|{archive,out/'implementation-status.json',out/'qualification-report.md',out/'dependency-inventory.json',out/'uncovered-requirements.json'}
files.update(p for p in (r/'evidence/docker').rglob('*') if p.is_file());files.update(p for p in out.rglob('*.log'));files.update(p for p in out.rglob('*.json') if 'jvm-classes' not in p.parts);files.update(r/a['path'] for a in artifacts)
(out/'artifact-checksums.txt').write_text(''.join(hashfile(p)+'  '+str(p.relative_to(r))+'\n' for p in sorted(files) if p.is_file()))
print('Recorded actual automated results, separate device/external gates, coverage and artifact checksums.')
